### ISSUE TITLE
[meta] support MPI and multi-device

### ISSUE THREAD

**Issue by t-hishinuma** [ricosjp/monolish#44]
- [ ] get/set device num. I/F
- [ ] enable option of mpicc in cmake : `-DUSE_MPI`
- [ ] Input MPI_COMM I/F
- [ ] implement BLAS Lv.1
- [ ] implement global size of Dense
- [ ] implement BLAS Lv.2(Dense)
- [ ] Checking the working of CG in Dense (precon = none)
- [ ] implement `comm_table` of CRS
- [ ] implement BLAS Lv.2(CRS)
- [ ] Checking the working of CG in CRS (precon = none)
