### ISSUE TITLE
[meta] change list to support C++17

### ISSUE THREAD

**Issue by t-hishinuma** [ricosjp/monolish#55]
- [x] nodiscard : https://en.cppreference.com/w/cpp/language/attributes/nodiscard  `dot()`, `nrm()`, `is_*`,  `build_with_*` #58 
- [ ] maybe_unused : https://en.cppreference.com/w/cpp/language/attributes/maybe_unused
- [x] simplified nested namespaces: https://en.cppreference.com/w/cpp/language/namespace #60 
- [ ] `std::clamp` for `monolish::XX` : https://en.cppreference.com/w/cpp/algorithm/clamp
